## Tarea 4 - SENL Cobb Douglas

En esta tarea, debemos solucionar una función Cobb-Douglas intentando varios métodos y parámetros.

In [94]:
import numpy as np
from scipy.optimize import root

# parámetros
A1, A2 = 1.2, 0.9
alpha1, alpha2 = 0.3, 0.6
Kbar, Lbar = 100.0, 50.0

def F(x):
    K1, L1, r, w = x
    K2 = Kbar - K1
    L2 = Lbar - L1
    
    # ecuaciones de equilibrio
    f1 = r - A1*alpha1*(np.sign(K1) * (np.abs(K1))**(alpha1-1))*(np.sign(L1) * (np.abs(L1))**(1-alpha1))
    f2 = r - A2*alpha2*(K2**(alpha2-1))*(L2**(1-alpha2))
    f3 = w - 1*A1*(1-alpha1)*(K1**alpha1)*(L1**(-alpha1))
    f4 = w - A2*(1-alpha2)*(K2**alpha2)*(L2**(-alpha2))
    
    return [f1, f2, f3, f4]

# condición inicial
x0 = [50, 25, 0.5, 0.5]

# solucion del sistema no lineal
sol = root(F, x0, method='hybr')
#sol = root(F, x0)

print(sol)
print("---------------")
print("K1 = %.6f, L1 = %.6f, r = %.6f, w = %.6f" % tuple(sol.x))

# capital y trabajo del segundo sector
K2, L2 = Kbar - sol.x[0], Lbar - sol.x[1]
print("K2 = %.6f, L2 = %.6f" % (K2, L2))

 message: The iteration is not making good progress, as measured by the
            improvement from the last ten iterations.
 success: False
  status: 5
     fun: [ 2.784e-01  9.076e-02 -5.342e-01 -4.566e-02]
       x: [ 5.000e+01  2.500e+01  5.000e-01  5.000e-01]
    nfev: 19
    fjac: [[-3.076e-01  3.246e-01  6.152e-01 -6.492e-01]
           [-2.819e-01 -3.151e-02 -7.521e-01 -5.949e-01]
           [ 6.649e-01  7.140e-01 -1.785e-01 -1.272e-01]
           [ 6.195e-01 -6.195e-01  1.549e-01 -4.565e-01]]
       r: [       nan        nan        nan        nan        nan
                  nan        nan        nan        nan        nan]
     qtf: [-3.552e-01  3.476e-01  3.511e-01  5.436e-02]
---------------
K1 = 50.000000, L1 = 25.000000, r = 0.500000, w = 0.500000
K2 = 50.000000, L2 = 25.000000

C:\Users\Seba RC\AppData\Local\Temp\ipykernel_20140\1178583144.py:17: RuntimeWarning: invalid value encountered in scalar power
  f3 = w - 1*A1*(1-alpha1)*(K1**alpha1)*(L1**(-alpha1))

La principal pregunta es... como podemos encontrar parámetros que nos den una solución?

Pensemos lógicamente en esto, y saquemos algunas condiciones...

- r, el cambio del costo de capital, no puede ser negativo
- w, el cambio del salario del trabajo, tampoco puede ser negativo
- La produccion en si, Y, para cada sector, no puede ser negativa
- Lo mismo se repite para todas las otras variables, L, W, alpha y beta

Entonces sabemos que ninguna variable puede ser negativa.

Probemos entonces, otros parametros iniciales.

Sabemos que ambos sectores son diferentes, debido a que $ \alpha_1 $ y $ \alpha_2 $ son diferentes. Dado esto, podemos modificar los valores iniciales de L1 y K1, y derivar los valores iniciales CORRECTOS de r y w usando estos. 

Asumiendo un equilibrio...

Con un alpha de 0.3, se puede decir que el sector 1 necesita menos capital (K1) que el sector 2. Asignemosle menos al sector 1..
Con un alpha de 0.6, se puede decir que el sector 1 es mejor usando la mano de obra (L1) que el sector 2. Le asignaremos mas al sector 1 

Por esto, los valores L1 y K1, o los valores de r y w, deberian cambiar. Asignar valores iguales en terminos de proporcion para cada uno seria el principal error.

Demosle una proporcion de 70% a L1 en Lbar, y 30% a K1 en Kbar. Con esto, $L_1 = 35$ y $K1 = 30$

In [123]:
# Con A1 = 1.2, a1 = 0.3, K1 = 30, L1 = 35,  
A1 = 1.2
alpha1 = 0.3
K1 = 30
L1 = 35

r = A1* alpha1 * (L1 ** (alpha1 - 1)) * (K1 ** (1 - alpha1))
w = A1* (1-alpha1) * (L1 ** (alpha1 - 1)) * (K1 ** (- alpha1))
x0 = [L1, K1, r, w]
x0

[35, 30, 0.32317648124403325, 0.02513594854120259]

In [96]:
sol1 = root(F, x0, method='hybr')
#sol = root(F, x0)

print(sol1)
print("---------------")
print("K1 = %.6f, L1 = %.6f, r = %.6f, w = %.6f" % tuple(sol1.x))

# capital y trabajo del segundo sector
K2, L2 = Kbar - sol1.x[0], Lbar - sol1.x[1]
print("K2 = %.6f, L2 = %.6f" % (K2, L2))

 message: The solution converged.
 success: True
  status: 1
     fun: [-2.220e-15 -4.663e-15  6.661e-16  1.843e-14]
       x: [ 5.628e+01  4.092e+01  2.880e-01  9.243e-01]
    nfev: 44
    fjac: [[-2.703e-01  1.787e-01  3.644e-01 -8.730e-01]
           [-5.290e-01 -9.594e-02  7.171e-01  4.435e-01]
           [-5.094e-01 -7.559e-01 -3.806e-01 -1.558e-01]
           [ 6.225e-01 -6.225e-01  4.562e-01 -1.297e-01]]
       r: [-1.361e-02  5.787e-02 -9.139e-02 -5.080e-01 -1.986e-02
           -6.253e-01  1.161e+00 -1.265e+00 -5.364e-01  3.264e-01]
     qtf: [-1.172e-10  7.548e-11  1.096e-11 -3.862e-12]
---------------
K1 = 56.283360, L1 = 40.919170, r = 0.287995, w = 0.924305
K2 = 43.716640, L2 = 9.080830

C:\Users\Seba RC\AppData\Local\Temp\ipykernel_20140\1178583144.py:17: RuntimeWarning: invalid value encountered in scalar power
  f3 = w - 1*A1*(1-alpha1)*(K1**alpha1)*(L1**(-alpha1))

Y ahi podemos ver que nuestros resultados estan correctos.

Entonces el error principalmente estaba en x0, la solucion inicial. Probemos otras soluciones iniciales.

In [97]:
from time import time
import pandas as pd

Kbar = 100.0
Lbar = 50.0
A1 = 1.2
alpha1 = 0.3

# 20 semillas, y listas para cada dato
semillas_x0 = []
K1List = []
L1List = []
rList = []
wList = []
timeTakenList = []
statusList = []
L2List = []
K2List = []

for i in range(20):
    # Esta distribucion nos da un numero entre los rangos deseados, generando algo de variacion entre las semillas
    k0 = np.random.uniform(0.25 * Kbar, 0.35 * Kbar)
    l0 = np.random.uniform(0.65 * Lbar, 0.75 * Lbar)
    
    # r y w seran calculados manualmente
    r0 = A1* alpha1 * (l0 ** (alpha1 - 1)) * (k0 ** (1 - alpha1))
    w0 = A1* (1-alpha1) * (l0 ** (alpha1 - 1)) * (k0 ** (- alpha1))
    
    # Redondeamos para que sea legible, pero en el código real usa los floats completos
    lista_x0 = [round(k0, 2), round(l0, 2), round(r0, 2), round(w0, 3)]
    semillas_x0.append(lista_x0)
    
    print(f"Semilla {i+1:<2} | {lista_x0}")

Semilla 1  | [27.81, 36.78, 0.3, 0.025]
Semilla 2  | [26.98, 35.92, 0.29, 0.025]
Semilla 3  | [29.57, 37.07, 0.31, 0.024]
Semilla 4  | [33.38, 34.32, 0.35, 0.025]
Semilla 5  | [28.23, 34.76, 0.31, 0.026]
Semilla 6  | [28.33, 35.9, 0.3, 0.025]
Semilla 7  | [26.25, 37.27, 0.28, 0.025]
Semilla 8  | [28.95, 37.2, 0.3, 0.024]
Semilla 9  | [27.05, 33.95, 0.31, 0.026]
Semilla 10 | [34.15, 32.61, 0.37, 0.025]
Semilla 11 | [31.07, 33.43, 0.34, 0.026]
Semilla 12 | [29.4, 34.65, 0.32, 0.025]
Semilla 13 | [29.21, 34.53, 0.32, 0.026]
Semilla 14 | [30.62, 32.98, 0.34, 0.026]
Semilla 15 | [34.11, 34.15, 0.36, 0.025]
Semilla 16 | [34.37, 34.9, 0.36, 0.024]
Semilla 17 | [25.41, 33.0, 0.3, 0.028]
Semilla 18 | [25.47, 36.36, 0.28, 0.026]
Semilla 19 | [34.0, 34.59, 0.36, 0.024]
Semilla 20 | [31.18, 35.74, 0.33, 0.024]

Veamos los resultados:

In [98]:
for i in semillas_x0:
    timeStart = time()
    sol = root(F, i, method="hybr")
    timeEnd = time()
    timeTaken = timeEnd - timeStart
    K1List.append(sol.x[0])
    L1List.append(sol.x[1])
    rList.append(sol.x[2])
    wList.append(sol.x[3])
    timeTakenList.append(timeTaken)
    statusList.append(sol.success)
    K2List.append(Kbar - sol.x[0])
    L2List.append(Lbar - sol.x[1])


dfResults1 = pd.DataFrame(data={
    'Semilla': semillas_x0,
    'K1': K1List,
    'L1': L1List,
    'r': rList,
    'w': wList,
    'timeTaken': timeTakenList,
    'status': statusList,
    'K2': K2List,
    'L2': L2List,
})

display(dfResults1)

C:\Users\Seba RC\AppData\Local\Temp\ipykernel_20140\1178583144.py:16: RuntimeWarning: invalid value encountered in scalar power
  f2 = r - A2*alpha2*(K2**(alpha2-1))*(L2**(1-alpha2))
C:\Users\Seba RC\AppData\Local\Temp\ipykernel_20140\1178583144.py:18: RuntimeWarning: invalid value encountered in scalar power
  f4 = w - A2*(1-alpha2)*(K2**alpha2)*(L2**(-alpha2))

,Semilla,K1,L1,r,w,timeTaken,status,K2,L2
0,"[27.81, 36.78, 0.3, 0.025]",56.28336,40.91917,0.287995,0.924305,0.000000,True,43.71664,9.08083
1,"[26.98, 35.92, 0.29, 0.025]",56.28336,40.91917,0.287995,0.924305,0.000997,True,43.71664,9.08083
2,"[29.57, 37.07, 0.31, 0.024]",56.28336,40.91917,0.287995,0.924305,0.000000,True,43.71664,9.08083
3,"[33.38, 34.32, 0.35, 0.025]",56.28336,40.91917,0.287995,0.924305,0.000000,True,43.71664,9.08083
4,"[28.23, 34.76, 0.31, 0.026]",56.28336,40.91917,0.287995,0.924305,0.000000,True,43.71664,9.08083
5,"[28.33, 35.9, 0.3, 0.025]",56.28336,40.91917,0.287995,0.924305,0.000000,True,43.71664,9.08083
6,"[26.25, 37.27, 0.28, 0.025]",56.28336,40.91917,0.287995,0.924305,0.000000,True,43.71664,9.08083
7,"[28.95, 37.2, 0.3, 0.024]",56.28336,40.91917,0.287995,0.924305,0.000540,True,43.71664,9.08083
8,"[27.05, 33.95, 0.31, 0.026]",56.28336,40.91917,0.287995,0.924305,0.000000,True,43.71664,9.08083
9,"[34.15, 32.61, 0.37, 0.025]",56.28336,40.91917,0.287995,0.924305,0.000000,True,43.71664,9.08083
10,"[31.07, 33.43, 0.34, 0.026]",56.28336,40.91917,0.287995,0.924305,0.000997,True,43.71664,9.08083
11,"[29.4, 34.65, 0.32, 0.025]",56.28336,40.91917,0.287995,0.924305,0.000000,True,43.71664,9.08083
12,"[29.21, 34.53, 0.32, 0.026]",56.28336,40.91917,0.287995,0.924305,0.000000,True,43.71664,9.08083
13,"[30.62, 32.98, 0.34, 0.026]",56.28336,40.91917,0.287995,0.924305,0.000998,True,43.71664,9.08083
14,"[34.11, 34.15, 0.36, 0.025]",56.28336,40.91917,0.287995,0.924305,0.000000,True,43.71664,9.08083
15,"[34.37, 34.9, 0.36, 0.024]",56.28336,40.91917,0.287995,0.924305,0.000022,True,43.71664,9.08083
16,"[25.41, 33.0, 0.3, 0.028]",56.28336,40.91917,0.287995,0.924305,0.000000,True,43.71664,9.08083
17,"[25.47, 36.36, 0.28, 0.026]",56.28336,40.91917,0.287995,0.924305,0.000000,True,43.71664,9.08083
18,"[34.0, 34.59, 0.36, 0.024]",56.28336,40.91917,0.287995,0.924305,0.000000,True,43.71664,9.08083
19,"[31.18, 35.74, 0.33, 0.024]",56.28336,40.91917,0.287995,0.924305,0.000989,True,43.71664,9.08083

Genial, eso funciona ahora.

Para que nuestro punto sea mas valido aun, veamos como cambia mientras invertimos alpha1, alpha2, A1 y A2:

In [99]:
A1, A2 = 0.9, 1.2
alpha1, alpha2 = 0.6, 0.3
Kbar, Lbar = 100.0, 50.0
# redefinir la funcion con los nuevos parametros

def F(x):
    K1, L1, r, w = x
    K2 = Kbar - K1
    L2 = Lbar - L1
    
    # ecuaciones de equilibrio
    f1 = r - A1*alpha1*(np.sign(K1) * (np.abs(K1))**(alpha1-1))*(np.sign(L1) * (np.abs(L1))**(1-alpha1))
    f2 = r - A2*alpha2*(K2**(alpha2-1))*(L2**(1-alpha2))
    f3 = w - 1*A1*(1-alpha1)*(K1**alpha1)*(L1**(-alpha1))
    f4 = w - A2*(1-alpha2)*(K2**alpha2)*(L2**(-alpha2))
    
    return [f1, f2, f3, f4]


# 20 semillas, y listas para cada dato
semillas_x0 = []
K1List = []
L1List = []
rList = []
wList = []
timeTakenList = []
statusList = []
L2List = []
K2List = []

for i in range(20):
    # Esta distribucion nos da un numero entre los rangos deseados, generando algo de variacion entre las semillas
    k0 = np.random.uniform(0.65 * Kbar, 0.75 * Kbar) # invertimos los rangos para que nos funcione con alpha = 0.6
    l0 = np.random.uniform(0.25 * Lbar, 0.35 * Lbar)
    
    # r y w seran calculados manualmente
    r0 = A1* alpha1 * (l0 ** (alpha1 - 1)) * (k0 ** (1 - alpha1))
    w0 = A1* (1-alpha1) * (l0 ** (alpha1 - 1)) * (k0 ** (- alpha1))
    
    # Redondeamos para que sea legible, pero en el código real usa los floats completos
    lista_x0 = [round(k0, 2), round(l0, 2), round(r0, 2), round(w0, 3)]
    semillas_x0.append(lista_x0)
    
    print(f"Semilla {i+1:<2} | {lista_x0}")

for i in semillas_x0:
    timeStart = time()
    sol = root(F, i, method="hybr")
    timeEnd = time()
    timeTaken = timeEnd - timeStart
    K1List.append(sol.x[0])
    L1List.append(sol.x[1])
    rList.append(sol.x[2])
    wList.append(sol.x[3])
    timeTakenList.append(timeTaken)
    statusList.append(sol.success)
    K2List.append(Kbar - sol.x[0])
    L2List.append(Lbar - sol.x[1])


dfResults2 = pd.DataFrame(data={
    'Semilla': semillas_x0,
    'K1': K1List,
    'L1': L1List,
    'r': rList,
    'w': wList,
    'timeTaken': timeTakenList,
    'status': statusList,
    'K2': K2List,
    'L2': L2List,
})

display(dfResults2)

Semilla 1  | [74.51, 16.19, 0.99, 0.009]
Semilla 2  | [65.93, 17.38, 0.92, 0.009]
Semilla 3  | [73.63, 13.68, 1.06, 0.01]
Semilla 4  | [68.88, 16.11, 0.97, 0.009]
Semilla 5  | [69.98, 13.77, 1.03, 0.01]
Semilla 6  | [69.29, 16.05, 0.97, 0.009]
Semilla 7  | [69.85, 15.09, 1.0, 0.01]
Semilla 8  | [71.84, 15.17, 1.01, 0.009]
Semilla 9  | [66.2, 13.2, 1.03, 0.01]
Semilla 10 | [73.41, 16.96, 0.97, 0.009]
Semilla 11 | [71.59, 13.76, 1.04, 0.01]
Semilla 12 | [74.56, 13.69, 1.06, 0.01]
Semilla 13 | [73.26, 15.46, 1.01, 0.009]
Semilla 14 | [69.65, 15.92, 0.97, 0.009]
Semilla 15 | [73.25, 16.99, 0.97, 0.009]
Semilla 16 | [68.97, 15.61, 0.98, 0.009]
Semilla 17 | [74.08, 12.93, 1.09, 0.01]
Semilla 18 | [70.15, 15.48, 0.99, 0.009]
Semilla 19 | [66.19, 14.64, 0.99, 0.01]
Semilla 20 | [69.54, 14.43, 1.01, 0.01]

,Semilla,K1,L1,r,w,timeTaken,status,K2,L2
0,"[74.51, 16.19, 0.99, 0.009]",43.71664,9.08083,0.287995,0.924305,0.001004,True,56.28336,40.91917
1,"[65.93, 17.38, 0.92, 0.009]",43.71664,9.08083,0.287995,0.924305,0.000000,True,56.28336,40.91917
2,"[73.63, 13.68, 1.06, 0.01]",43.71664,9.08083,0.287995,0.924305,0.000538,True,56.28336,40.91917
3,"[68.88, 16.11, 0.97, 0.009]",43.71664,9.08083,0.287995,0.924305,0.000000,True,56.28336,40.91917
4,"[69.98, 13.77, 1.03, 0.01]",43.71664,9.08083,0.287995,0.924305,0.000000,True,56.28336,40.91917
5,"[69.29, 16.05, 0.97, 0.009]",43.71664,9.08083,0.287995,0.924305,0.000000,True,56.28336,40.91917
6,"[69.85, 15.09, 1.0, 0.01]",43.71664,9.08083,0.287995,0.924305,0.000999,True,56.28336,40.91917
7,"[71.84, 15.17, 1.01, 0.009]",43.71664,9.08083,0.287995,0.924305,0.000000,True,56.28336,40.91917
8,"[66.2, 13.2, 1.03, 0.01]",43.71664,9.08083,0.287995,0.924305,0.000000,True,56.28336,40.91917
9,"[73.41, 16.96, 0.97, 0.009]",43.71664,9.08083,0.287995,0.924305,0.000000,True,56.28336,40.91917
10,"[71.59, 13.76, 1.04, 0.01]",43.71664,9.08083,0.287995,0.924305,0.001000,True,56.28336,40.91917
11,"[74.56, 13.69, 1.06, 0.01]",43.71664,9.08083,0.287995,0.924305,0.000000,True,56.28336,40.91917
12,"[73.26, 15.46, 1.01, 0.009]",43.71664,9.08083,0.287995,0.924305,0.000536,True,56.28336,40.91917
13,"[69.65, 15.92, 0.97, 0.009]",43.71664,9.08083,0.287995,0.924305,0.000000,True,56.28336,40.91917
14,"[73.25, 16.99, 0.97, 0.009]",43.71664,9.08083,0.287995,0.924305,0.000000,True,56.28336,40.91917
15,"[68.97, 15.61, 0.98, 0.009]",43.71664,9.08083,0.287995,0.924305,0.000000,True,56.28336,40.91917
16,"[74.08, 12.93, 1.09, 0.01]",43.71664,9.08083,0.287995,0.924305,0.000994,True,56.28336,40.91917
17,"[70.15, 15.48, 0.99, 0.009]",43.71664,9.08083,0.287995,0.924305,0.000000,True,56.28336,40.91917
18,"[66.19, 14.64, 0.99, 0.01]",43.71664,9.08083,0.287995,0.924305,0.000000,True,56.28336,40.91917
19,"[69.54, 14.43, 1.01, 0.01]",43.71664,9.08083,0.287995,0.924305,0.000000,True,56.28336,40.91917

Tambien funciona!

Ahora que sabemos como funciona la funcion, volvamos a los parametros originales y la solucion simple que encontramos y hagamos pruebas de los distintos metodos para encontrar raices.

In [100]:
# parámetros
A1, A2 = 1.2, 0.9
alpha1, alpha2 = 0.3, 0.6
Kbar, Lbar = 100.0, 50.0

def F(x):
    K1, L1, r, w = x
    K2 = Kbar - K1
    L2 = Lbar - L1
    
    # ecuaciones de equilibrio
    f1 = r - A1*alpha1*(np.sign(K1) * (np.abs(K1))**(alpha1-1))*(np.sign(L1) * (np.abs(L1))**(1-alpha1))
    f2 = r - A2*alpha2*(K2**(alpha2-1))*(L2**(1-alpha2))
    f3 = w - 1*A1*(1-alpha1)*(K1**alpha1)*(L1**(-alpha1))
    f4 = w - A2*(1-alpha2)*(K2**alpha2)*(L2**(-alpha2))
    
    return [f1, f2, f3, f4]

K1 = 30
L1 = 35

r = A1* alpha1 * (L1 ** (alpha1 - 1)) * (K1 ** (1 - alpha1))
w = A1* (1-alpha1) * (L1 ** (alpha1 - 1)) * (K1 ** (- alpha1))
x0 = [L1, K1, r, w]

In [121]:
K1List = []
L1List = []
rList = []
wList = []
timeTakenList = []
statusList = []
L2List = []
K2List = []
Method = ['hybr','lm','broyden1','broyden2','anderson','linearmixing','excitingmixing','krylov','df-sane'] # diagbroyden simplemente no funciona con estos valores

for method in Method:
    timeStart = time()
    try:
        sol = root(F, x0, method=method)
        timeEnd = time()
        timeTaken = timeEnd - timeStart
        K1List.append(sol.x[0])
        L1List.append(sol.x[1])
        rList.append(sol.x[2])
        wList.append(sol.x[3])
        timeTakenList.append(timeTaken)
        statusList.append(sol.success)
        K2List.append(Kbar - sol.x[0])
        L2List.append(Lbar - sol.x[1])
    except ValueError:
        sol = root(F, x0, method=method)
        timeEnd = time()
        timeTaken = timeEnd - timeStart
        K1List.append('Failed')
        L1List.append('Failed')
        rList.append('Failed')
        wList.append('Failed')
        timeTakenList.append(timeTaken)
        statusList.append('Failed')
        K2List.append('Failed')
        L2List.append('Failed')

x0forDf = [x0] * len(Method)

print(x0forDf)

dfResults3 = pd.DataFrame(data={
    'Semilla': x0forDf,
    'K1': K1List,
    'L1': L1List,
    'r': rList,
    'w': wList,
    'timeTaken': timeTakenList,
    'status': statusList,
    'K2': K2List,
    'L2': L2List,
    'Metodo': Method
})

display(dfResults3)

C:\Users\Seba RC\AppData\Local\Temp\ipykernel_20140\2607354781.py:14: RuntimeWarning: invalid value encountered in scalar power
  f3 = w - 1*A1*(1-alpha1)*(K1**alpha1)*(L1**(-alpha1))
C:\Users\Seba RC\AppData\Local\Temp\ipykernel_20140\2607354781.py:13: RuntimeWarning: invalid value encountered in scalar power
  f2 = r - A2*alpha2*(K2**(alpha2-1))*(L2**(1-alpha2))
C:\Users\Seba RC\AppData\Local\Temp\ipykernel_20140\2607354781.py:15: RuntimeWarning: invalid value encountered in scalar power
  f4 = w - A2*(1-alpha2)*(K2**alpha2)*(L2**(-alpha2))
c:\Python311\Lib\site-packages\scipy\optimize\_nonlin.py:913: RuntimeWarning: invalid value encountered in divide
  d = v / vdot(df, v)
c:\Python311\Lib\site-packages\scipy\optimize\_nonlin.py:974: RuntimeWarning: invalid value encountered in divide
  d = v / df_norm**2

[[35, 30, 0.32317648124403325, 0.02513594854120259], [35, 30, 0.32317648124403325, 0.02513594854120259], [35, 30, 0.32317648124403325, 0.02513594854120259], [35, 30, 0.32317648124403325, 0.02513594854120259], [35, 30, 0.32317648124403325, 0.02513594854120259], [35, 30, 0.32317648124403325, 0.02513594854120259], [35, 30, 0.32317648124403325, 0.02513594854120259], [35, 30, 0.32317648124403325, 0.02513594854120259], [35, 30, 0.32317648124403325, 0.02513594854120259]]

,Semilla,K1,L1,r,w,timeTaken,status,K2,L2,Metodo
0,"[35, 30, 0.32317648124403325, 0.02513594854120...",56.283360,40.919170,0.287995,0.924305,0.000000,True,43.716640,9.080830,hybr
1,"[35, 30, 0.32317648124403325, 0.02513594854120...",56.283360,40.919170,0.287995,0.924305,0.001997,True,43.716640,9.080830,lm
2,"[35, 30, 0.32317648124403325, 0.02513594854120...",49.960039,49.527653,19.705419,-17.942291,0.166476,False,50.039961,0.472347,broyden1
3,"[35, 30, 0.32317648124403325, 0.02513594854120...",46.457672,45.460171,-6.614679,-8.587271,0.193000,False,53.542328,4.539829,broyden2
4,"[35, 30, 0.32317648124403325, 0.02513594854120...",56.283335,40.919165,0.287995,0.924305,0.016635,True,43.716665,9.080835,anderson
5,"[35, 30, 0.32317648124403325, 0.02513594854120...",35.000000,29.712263,-17.455306,-14.641801,0.224088,False,65.000000,20.287737,linearmixing
6,"[35, 30, 0.32317648124403325, 0.02513594854120...",17.223690,11.918018,-32.979412,-30.007555,0.117825,False,82.776310,38.081982,excitingmixing
7,"[35, 30, 0.32317648124403325, 0.02513594854120...",56.283209,40.919125,0.287995,0.924305,0.165248,True,43.716791,9.080875,krylov
8,"[35, 30, 0.32317648124403325, 0.02513594854120...",42.035962,36.559835,0.327748,0.866332,0.034297,False,57.964038,13.440165,df-sane